### ISSUE TITLE
Data management(vuex)

### ISSUE THREAD

**Issue by tombiers** [Viva-con-Agua/bloob-frontend#6]
Certain data has to be kept in the front end:
- UUIDs of receivers/groups of receivers  #1 
- sender selection #2 
- sender address selection #3 
- subject line #4 
- email body #4

**Comment by tombiers** [comment]
also needed to save user data received from the back-end

**Comment by mymymario** [comment]
Created branch [feature/vuex-store](https://github.com/Viva-con-Agua/bloob-frontend/tree/feature/vuex-store) for the issue.

**Comment by tombiers** [comment]
implement vuex-mosaico-event handling in [feature/vuex-store](https://github.com/Viva-con-Agua/bloob-frontend/tree/feature/vuex-store), as seen in master branch
